# Generated by Django 5.2.4 on 2025-12-01 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneverification'),
        ('orders', '0006_order_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to='orders.region'),
        ),
    ]
