# Generated by Django 5.2.4 on 2025-11-30 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailnotification_receipt_pdf'),
        ('orders', '0002_order_delivered_at_order_estimated_delivery_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
