# Generated by Django 5.2.6 on 2025-01-05 00:00

from django.db import migrations


def seed_regions(apps, schema_editor):
    Region = apps.get_model("orders", "Region")
    defaults = [
        ("north", "North Vancouver", 0, 5),
        ("west", "West Vancouver", 1, 5),
        ("east", "East Vancouver", 2, 5),
        ("south", "South Vancouver", 3, 5),
        ("center", "Vancouver Center", 4, 5),
    ]
    for code, name, weekday, min_orders in defaults:
        Region.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "delivery_weekday": weekday,
                "min_orders": min_orders,
            },
        )


def noop_reverse(apps, schema_editor):
    # Keep seeded regions intact on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_region"),
    ]

    operations = [
        migrations.RunPython(seed_regions, reverse_code=noop_reverse),
    ]
