# Generated by Django 5.2.4 on 2025-12-01 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_seed_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.region'),
        ),
    ]
