# Generated by Django 5.2.8 on 2025-12-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
