# Generated by Django 5.2.6 on 2025-12-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_latitude_order_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("delivery", "Delivery")], default="delivery", max_length=20
            ),
        ),
    ]
