# Generated by Django 5.2.6 on 2025-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buzz_code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
