# Generated by Django 5.2.6 on 2025-12-05 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_deliveryproof"),
        ("orders", "0008_alter_order_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryroute",
            name="merged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryroute",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_children",
                to="delivery.deliveryroute",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="min_stops_for_dedicated_route",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum stops before we keep this driver separate. Below this, dispatch can merge with another route.",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="operating_weekdays",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Weekdays the driver is normally available (0=Mon ... 6=Sun)",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="preferred_region",
            field=models.ForeignKey(
                blank=True,
                help_text="Recommended primary direction/region for this driver",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_drivers",
                to="orders.region",
            ),
        ),
    ]
