# Generated by Django 5.2.6 on 2025-11-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Main product image (stored in S3 or local MEDIA_ROOT).",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
