# Generated by Django 5.2.4 on 2025-02-07 00:00

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def migrate_categories(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Category = apps.get_model("products", "Category")

    for product in Product.objects.all():
        name = (product.category or "").strip()
        if not name:
            continue
        slug = slugify(name)[:50]
        category, _created = Category.objects.get_or_create(
            slug=slug,
            defaults={"name": name},
        )
        if category.name != name:
            category.name = name
            category.save(update_fields=["name"])
        product.category_fk = category
        product.save(update_fields=["category_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category_fk",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="products.category"),
        ),
        migrations.RunPython(migrate_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="category_fk",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="products", to="products.category"),
        ),
    ]
