# Generated by Django 5.2.4 on 2025-02-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_category_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Gallery image stored in S3 or media.",
                null=True,
                upload_to="products/gallery/",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(blank=True, help_text="Optional external image URL (legacy)."),
        ),
    ]
