# Generated by Django 5.2.6 on 2025-11-24 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("cover_image_url", models.URLField(blank=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-published_at", "-id"],
            },
        ),
    ]
