# Generated by Django 5.2.8 on 2025-11-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_order_i_4d9364_idx",
            old_name="payments_pay_order_i_7f2e26_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_stripe__6fe52c_idx",
            old_name="payments_pay_stripe__2d095f_idx",
        ),
    ]
